import { FilesetResolver, PoseLandmarker, HandLandmarker, DrawingUtils } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/vision_bundle.mjs";

const WASM_URL="https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm";
const POSE_MODELS={full:"https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task",lite:"https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task"};
const HAND_MODEL="https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";
const SAMPLE_FPS=15, MAX_SAMPLES=900, MIN_VIS=.35;
const P={LS:11,RS:12,LE:13,RE:14,LW:15,RW:16,LH:23,RH:24,LK:25,RK:26,LA:27,RA:28};
const ids=["videoFile","dropZone","handedness","viewDirection","serveType","modelQuality","clipStart","clipEnd","analyzeButton","cancelButton","progressWrap","progressText","progressPercent","analysisProgress","notice","modelStatus","sourceVideo","overlayCanvas","videoStage","playPauseButton","prevFrameButton","nextFrameButton","timeline","timeDisplay","playbackRate","skeletonToggle","handToggle","ballToggle","jumpHitButton","setHitButton","hitTimeLabel","ballRadius","ballRadiusLabel","selectBallButton","trackBallButton","clearBallButton","youtubeUrl","loadYoutubeButton","youtubeFrameWrap","youtubeFrame","youtubePlaceholder","exportCsvButton","exportImageButton","elbowMetric","handSpeedMetric","contactOffsetMetric","ballSpeedMetric","rpmMetric","rpmConfidence","detectionMetric","angleChart","chartEmpty","observationText","phaseButtons"];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const ctx=el.overlayCanvas.getContext("2d",{willReadFrequently:true});
const work=document.createElement("canvas"), wctx=work.getContext("2d",{willReadFrequently:true});
let pose=null, hand=null, drawer=null, quality=null, analysis=null, url=null, raf=null, cancel=false, selectingBall=false, ballSeed=null, chart=null, tsBase=0;

const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));
const visible=p=>p&&((p.visibility??1)>=MIN_VIS);
const mid=(a,b)=>a&&b?{x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:((a.z||0)+(b.z||0))/2,visibility:Math.min(a.visibility??1,b.visibility??1)}:null;
function angle(a,b,c){if(![a,b,c].every(visible))return NaN;const u=[a.x-b.x,a.y-b.y,(a.z||0)-(b.z||0)],v=[c.x-b.x,c.y-b.y,(c.z||0)-(b.z||0)];const d=u[0]*v[0]+u[1]*v[1]+u[2]*v[2],lu=Math.hypot(...u),lv=Math.hypot(...v);return lu&&lv?Math.acos(clamp(d/(lu*lv),-1,1))*180/Math.PI:NaN}
function setNotice(t,type="info"){el.notice.textContent=t;el.notice.className=`notice${type==="info"?"":` ${type}`}`}
function status(t,s){el.modelStatus.textContent=t;el.modelStatus.className=`status-pill status-${s}`}
function fmt(v,d=2){return Number.isFinite(v)?v.toFixed(d):"—"}
function progress(done,total,text){const p=total?Math.round(done/total*100):0;el.analysisProgress.value=p;el.progressPercent.textContent=`${p}%`;el.progressText.textContent=text}
async function models(){if(pose&&hand&&quality===el.modelQuality.value)return;status("AI読込中","loading");const vision=await FilesetResolver.forVisionTasks(WASM_URL);pose?.close();hand?.close();pose=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:POSE_MODELS[el.modelQuality.value],delegate:"GPU"},runningMode:"VIDEO",numPoses:1,minPoseDetectionConfidence:.45,minPosePresenceConfidence:.45,minTrackingConfidence:.45});hand=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:HAND_MODEL,delegate:"GPU"},runningMode:"VIDEO",numHands:2,minHandDetectionConfidence:.35,minHandPresenceConfidence:.35,minTrackingConfidence:.35});quality=el.modelQuality.value;drawer=new DrawingUtils(ctx);status("AI準備完了","ready")}
function metrics(l,side){const left=side==="left",S=l[left?P.LS:P.RS],E=l[left?P.LE:P.RE],W=l[left?P.LW:P.RW],ls=l[P.LS],rs=l[P.RS],lh=l[P.LH],rh=l[P.RH],sm=mid(ls,rs),hm=mid(lh,rh);const torso=sm&&hm?Math.hypot(sm.x-hm.x,sm.y-hm.y):NaN;return{elbow:angle(S,E,W),knee:(angle(lh,l[P.LK],l[P.LA])+angle(rh,l[P.RK],l[P.RA]))/2,wristX:W?.x,wristY:W?.y,wristVis:W?.visibility??0,wristHigh:visible(W)&&visible(S)&&torso?(S.y-W.y)/torso:NaN,trunk:sm&&hm?Math.atan2(sm.x-hm.x,hm.y-sm.y)*180/Math.PI:NaN,hipY:hm?.y}}
function seek(t){const v=el.sourceVideo,target=clamp(t,0,Math.max(0,(v.duration||0)-.001));if(Math.abs(v.currentTime-target)<.002)return Promise.resolve();return new Promise((res,rej)=>{const to=setTimeout(()=>{clean();rej(Error("動画の移動がタイムアウトしました"))},5000),clean=()=>{clearTimeout(to);v.removeEventListener("seeked",ok);v.removeEventListener("error",bad)},ok=()=>{clean();res()},bad=()=>{clean();rej(Error("動画を読み取れません"))};v.addEventListener("seeked",ok,{once:true});v.addEventListener("error",bad,{once:true});v.currentTime=target})}
function nearest(t){if(!analysis?.frames.length)return-1;let best=0,d=Infinity;analysis.frames.forEach((f,i)=>{const x=Math.abs(f.time-t);if(x<d){d=x;best=i}});return best}
function hitEstimate(fr){const speeds=fr.map(()=>0);for(let i=1;i<fr.length;i++){const a=fr[i-1].m,b=fr[i].m,dt=fr[i].time-fr[i-1].time;if(a&&b&&dt>0&&Number.isFinite(a.wristX)&&Number.isFinite(b.wristX))speeds[i]=Math.hypot(b.wristX-a.wristX,b.wristY-a.wristY)/dt}const max=Math.max(...speeds,.001);let bi=-1,bs=-1;fr.forEach((f,i)=>{if(!f.m||f.m.wristVis<MIN_VIS)return;const s=.48*clamp((f.m.wristHigh+.1)/1.4)+.32*clamp((f.m.elbow-100)/80)+.2*clamp(speeds[i]/max);if(s>bs){bs=s;bi=i}});fr.forEach((f,i)=>f.wristSpeed=speeds[i]);return bi}
async function analyze(){const v=el.sourceVideo;if(!v.src)return;cancel=false;el.analyzeButton.disabled=true;el.cancelButton.hidden=false;el.progressWrap.hidden=false;v.pause();try{await models();const start=clamp(+el.clipStart.value||0,0,v.duration),end=clamp(+el.clipEnd.value||v.duration,start+.05,v.duration),dur=end-start;let n=Math.min(MAX_SAMPLES,Math.floor(dur*SAMPLE_FPS)+1),fps=(n-1)/dur;const frames=[];tsBase=Math.max(performance.now(),tsBase+1000);for(let i=0;i<n;i++){if(cancel)throw new DOMException("中止","AbortError");const time=start+(i/(n-1))*dur;await seek(time);const r=pose.detectForVideo(v,tsBase+i*1000/fps),lm=r.landmarks?.[0]?.map(x=>({...x}))||null;frames.push({time,landmarks:lm,m:lm?metrics(lm,el.handedness.value):null,hands:null,wristSpeed:0});progress(i+1,n,"身体33点を解析中");if(i%5===0)await new Promise(r=>setTimeout(r,0))}const hi=hitEstimate(frames);analysis={frames,hitIndex:hi,handedness:el.handedness.value,sampleFps:fps,ball:[],rpm:null,rpmConfidence:0};if(hi>=0){const range=Math.max(3,Math.round(.28*fps)),a=Math.max(0,hi-range),b=Math.min(n-1,hi+range);for(let i=a;i<=b;i++){if(cancel)throw new DOMException("中止","AbortError");await seek(frames[i].time);const r=hand.detectForVideo(v,tsBase+100000+i*1000/fps);frames[i].hands=chooseHand(r,frames[i].landmarks,analysis.handedness);progress(i-a+1,b-a+1,"打点付近の手21点を解析中")}}renderResults();if(hi>=0)await seek(frames[hi].time);setNotice("身体と手の解析が完了しました。次に打点付近でボールを指定してください。","success")}catch(e){console.error(e);setNotice(e.name==="AbortError"?"解析を中止しました。":e.message,"error")}finally{el.analyzeButton.disabled=false;el.cancelButton.hidden=true;setTimeout(()=>el.progressWrap.hidden=true,500)}}
function chooseHand(r,poseLm,side){if(!r.landmarks?.length)return null;const wi=side==="left"?P.LW:P.RW,pw=poseLm?.[wi];let bi=0,bd=Infinity;r.landmarks.forEach((h,i)=>{const w=h[0],d=pw?Math.hypot(w.x-pw.x,w.y-pw.y):i;if(d<bd){bd=d;bi=i}});return r.landmarks[bi].map(x=>({...x}))}
function render(){ctx.clearRect(0,0,el.overlayCanvas.width,el.overlayCanvas.height);if(!analysis)return;const i=nearest(el.sourceVideo.currentTime),f=analysis.frames[i];if(f?.landmarks&&el.skeletonToggle.checked){drawer.drawConnectors(f.landmarks,PoseLandmarker.POSE_CONNECTIONS,{color:"rgba(61,214,231,.92)",lineWidth:3});drawer.drawLandmarks(f.landmarks,{color:"#fff",fillColor:"#2563eb",radius:4})}if(f?.hands&&el.handToggle.checked){drawer.drawConnectors(f.hands,HandLandmarker.HAND_CONNECTIONS,{color:"#f97316",lineWidth:3});drawer.drawLandmarks(f.hands,{color:"#fff",fillColor:"#f97316",radius:3})}if(analysis.ball?.length&&el.ballToggle.checked){ctx.save();ctx.strokeStyle="#facc15";ctx.lineWidth=3;ctx.beginPath();analysis.ball.forEach((b,j)=>{const x=b.x*ctx.canvas.width,y=b.y*ctx.canvas.height;j?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();const b=ballAt(f.time);if(b){ctx.beginPath();ctx.arc(b.x*ctx.canvas.width,b.y*ctx.canvas.height,b.r,0,Math.PI*2);ctx.strokeStyle="#ef4444";ctx.stroke()}ctx.restore()}if(i===analysis.hitIndex){const w=f.landmarks?.[analysis.handedness==="left"?P.LW:P.RW];if(w){ctx.save();ctx.strokeStyle="#ef4444";ctx.lineWidth=4;ctx.beginPath();ctx.arc(w.x*ctx.canvas.width,w.y*ctx.canvas.height,24,0,Math.PI*2);ctx.stroke();ctx.restore()}}}
function ballAt(t){if(!analysis?.ball?.length)return null;return analysis.ball.reduce((a,b)=>Math.abs(b.time-t)<Math.abs(a.time-t)?b:a)}
function loop(){const v=el.sourceVideo,d=v.duration||0;el.timeDisplay.textContent=`${fmt(v.currentTime)} / ${fmt(d)} 秒`;if(d&&document.activeElement!==el.timeline)el.timeline.value=Math.round(v.currentTime/d*1000);el.playPauseButton.textContent=v.paused?"▶":"❚❚";render();raf=requestAnimationFrame(loop)}
function renderResults(){const fr=analysis.frames,rate=100*fr.filter(f=>f.landmarks).length/fr.length,h=fr[analysis.hitIndex];el.detectionMetric.textContent=`${fmt(rate,0)}%`;el.elbowMetric.textContent=h?.m&&Number.isFinite(h.m.elbow)?`${fmt(h.m.elbow,1)}°`:"—";el.handSpeedMetric.textContent=h?.wristSpeed?fmt(h.wristSpeed,3):"—";el.hitTimeLabel.textContent=h?`打点候補：${fmt(h.time)}秒`:"打点候補：未検出";el.jumpHitButton.disabled=!h;el.setHitButton.disabled=false;el.selectBallButton.disabled=!h;el.exportCsvButton.disabled=false;el.exportImageButton.disabled=false;updateBallMetrics();makeChart();phases();const notes=[];if(h?.m)notes.push(`打点候補は${fmt(h.time)}秒、利き腕の肘角度は${fmt(h.m.elbow,1)}°です。`);if(h?.hands)notes.push("打点付近で利き手の21点を検出しました。手のひらと指の向きを確認できます。");notes.push("ボール追跡後は、手とボール中心のずれ・速度・表面模様からの推定回転数を追加します。");el.observationText.innerHTML=`<ul>${notes.map(x=>`<li>${x}</li>`).join("")}</ul>`}
function updateBallMetrics(){const h=analysis?.frames?.[analysis.hitIndex],b=h?ballAt(h.time):null;if(b&&h?.hands){const palm=h.hands[9];el.contactOffsetMetric.textContent=fmt(Math.hypot(palm.x-b.x,palm.y-b.y)/(b.r/el.overlayCanvas.width),2)}else el.contactOffsetMetric.textContent="—";if(analysis?.ball?.length>1){const i=Math.max(1,analysis.ball.findIndex(x=>x.time>=(h?.time||0))),a=analysis.ball[i-1],c=analysis.ball[i],dt=c.time-a.time;el.ballSpeedMetric.textContent=dt>0?fmt(Math.hypot(c.x-a.x,c.y-a.y)/dt,3):"—"}else el.ballSpeedMetric.textContent="—";el.rpmMetric.textContent=Number.isFinite(analysis?.rpm)?`${fmt(analysis.rpm,0)} rpm`:"—";el.rpmConfidence.textContent=analysis?.rpmConfidence?`信頼度 ${Math.round(analysis.rpmConfidence*100)}%`:"ボール追跡後"}
function makeChart(){chart?.destroy();el.chartEmpty.hidden=true;chart=new Chart(el.angleChart,{type:"line",data:{labels:analysis.frames.map(f=>fmt(f.time)),datasets:[{label:"肘角度",data:analysis.frames.map(f=>Number.isFinite(f.m?.elbow)?f.m.elbow:null),pointRadius:0,borderWidth:2},{label:"手首速度",data:analysis.frames.map(f=>f.wristSpeed||null),pointRadius:0,borderWidth:2,yAxisID:"y1"}]},options:{responsive:true,maintainAspectRatio:false,animation:false,scales:{y:{title:{display:true,text:"角度（°）"}},y1:{position:"right",grid:{drawOnChartArea:false},title:{display:true,text:"速度（画面幅/秒）"}}},plugins:{legend:{position:"bottom"}}}})}
function phases(){el.phaseButtons.innerHTML="";if(analysis.hitIndex<0)return;[["構え",0],["テイクバック",Math.max(0,analysis.hitIndex-Math.round(.45*analysis.sampleFps))],["打点",analysis.hitIndex],["フォロースルー",Math.min(analysis.frames.length-1,analysis.hitIndex+Math.round(.3*analysis.sampleFps))],["着地",Math.min(analysis.frames.length-1,analysis.hitIndex+Math.round(.7*analysis.sampleFps))]].forEach(([name,i])=>{const b=document.createElement("button");b.className="phase-button";b.textContent=`${name} ${fmt(analysis.frames[i].time)}秒`;b.onclick=()=>seek(analysis.frames[i].time);el.phaseButtons.appendChild(b)})}
function canvasPoint(ev){const r=el.overlayCanvas.getBoundingClientRect();return{x:(ev.clientX-r.left)/r.width,y:(ev.clientY-r.top)/r.height}}
function selectBall(){selectingBall=true;el.videoStage.classList.add("selecting-ball");setNotice("動画上のボール中心をクリックしてください。","success")}
function setBall(ev){if(!selectingBall)return;const p=canvasPoint(ev),r=+el.ballRadius.value;ballSeed={time:el.sourceVideo.currentTime,x:p.x,y:p.y,r};selectingBall=false;el.videoStage.classList.remove("selecting-ball");el.trackBallButton.disabled=false;el.clearBallButton.disabled=false;setNotice("ボールを指定しました。「自動追跡・回転推定」を押してください。","success");render()}
function framePixels(){work.width=el.sourceVideo.videoWidth;work.height=el.sourceVideo.videoHeight;wctx.drawImage(el.sourceVideo,0,0,work.width,work.height);return wctx.getImageData(0,0,work.width,work.height)}
function sampleColor(img,cx,cy,r){let R=0,G=0,B=0,n=0;const x0=Math.max(0,Math.floor(cx-r*.55)),x1=Math.min(img.width-1,Math.ceil(cx+r*.55)),y0=Math.max(0,Math.floor(cy-r*.55)),y1=Math.min(img.height-1,Math.ceil(cy+r*.55));for(let y=y0;y<=y1;y+=3)for(let x=x0;x<=x1;x+=3)if((x-cx)**2+(y-cy)**2<(.55*r)**2){const k=4*(y*img.width+x);R+=img.data[k];G+=img.data[k+1];B+=img.data[k+2];n++}return[R/n,G/n,B/n]}
function locate(img,prev,target,r){let best={x:prev.x,y:prev.y,s:Infinity};const pr=Math.max(18,r*3),step=Math.max(2,Math.round(r/7));for(let y=Math.max(r,prev.y-pr);y<Math.min(img.height-r,prev.y+pr);y+=step)for(let x=Math.max(r,prev.x-pr);x<Math.min(img.width-r,prev.x+pr);x+=step){const c=sampleColor(img,x,y,r),dc=Math.hypot(c[0]-target[0],c[1]-target[1],c[2]-target[2]),motion=.08*Math.hypot(x-prev.x,y-prev.y);const s=dc+motion;if(s<best.s)best={x,y,s}}return best}
function ringSignature(img,cx,cy,r,n=36){const a=[];for(let i=0;i<n;i++){const th=2*Math.PI*i/n,x=Math.round(cx+.58*r*Math.cos(th)),y=Math.round(cy+.58*r*Math.sin(th)),k=4*(clamp(y,0,img.height-1)*img.width+clamp(x,0,img.width-1));a.push(.299*img.data[k]+.587*img.data[k+1]+.114*img.data[k+2])}const m=a.reduce((s,x)=>s+x,0)/n;return a.map(x=>x-m)}
function shiftScore(a,b,sh){let e=0;for(let i=0;i<a.length;i++){const d=a[i]-b[(i+sh+a.length)%a.length];e+=d*d}return e/a.length}
async function trackBall(){if(!ballSeed||!analysis)return;el.trackBallButton.disabled=true;el.progressWrap.hidden=false;try{const frames=analysis.frames,start=nearest(ballSeed.time),r=ballSeed.r,sx=ballSeed.x*el.sourceVideo.videoWidth,sy=ballSeed.y*el.sourceVideo.videoHeight;await seek(frames[start].time);let img=framePixels(),target=sampleColor(img,sx,sy,r),result=new Array(frames.length);result[start]={time:frames[start].time,x:ballSeed.x,y:ballSeed.y,r,score:0,sig:ringSignature(img,sx,sy,r)};for(const dir of [1,-1]){let prev={x:sx,y:sy};for(let i=start+dir;i>=0&&i<frames.length;i+=dir){if(cancel)break;await seek(frames[i].time);img=framePixels();const q=locate(img,prev,target,r);prev=q;result[i]={time:frames[i].time,x:q.x/img.width,y:q.y/img.height,r,score:q.s,sig:ringSignature(img,q.x,q.y,r)};progress(Math.abs(i-start),frames.length,`ボール追跡中 ${dir>0?"→":"←"}`);if(Math.abs(i-start)%5===0)await new Promise(r=>setTimeout(r,0))}}analysis.ball=result.filter(Boolean);estimateRpm();updateBallMetrics();render();setNotice("ボール追跡と回転推定が完了しました。軌跡と信頼度を確認してください。","success")}catch(e){console.error(e);setNotice(`ボール追跡に失敗しました：${e.message}`,"error")}finally{el.progressWrap.hidden=true;el.trackBallButton.disabled=false}}
function estimateRpm(){const vals=[],conf=[];for(let i=1;i<analysis.ball.length;i++){const a=analysis.ball[i-1],b=analysis.ball[i],dt=b.time-a.time;if(!a.sig||!b.sig||dt<=0)continue;let bs=Infinity,bsh=0;for(let sh=-8;sh<=8;sh++){const s=shiftScore(a.sig,b.sig,sh);if(s<bs){bs=s;bsh=sh}}const deg=bsh*360/a.sig.length,rpm=Math.abs(deg/dt)/6;if(rpm>20&&rpm<5000){vals.push(rpm);conf.push(1/(1+bs/250))}}if(vals.length){vals.sort((a,b)=>a-b);analysis.rpm=vals[Math.floor(vals.length/2)];analysis.rpmConfidence=conf.reduce((a,b)=>a+b,0)/conf.length}else{analysis.rpm=null;analysis.rpmConfidence=0}}
function clearBall(){ballSeed=null;if(analysis){analysis.ball=[];analysis.rpm=null;analysis.rpmConfidence=0}el.trackBallButton.disabled=true;el.clearBallButton.disabled=true;updateBallMetrics();render()}
function exportCsv(){if(!analysis)return;const head=["time_s","elbow_deg","wrist_speed","ball_x","ball_y","ball_r","hit","rpm_estimate","rpm_confidence"],rows=analysis.frames.map((f,i)=>{const b=ballAt(f.time);return[fmt(f.time,3),fmt(f.m?.elbow,2),fmt(f.wristSpeed,4),b?fmt(b.x,5):"",b?fmt(b.y,5):"",b?b.r:"",i===analysis.hitIndex?1:0,analysis.rpm??"",analysis.rpmConfidence??""]});const blob=new Blob(["\ufeff"+[head,...rows].map(r=>r.join(",")).join("\r\n")],{type:"text/csv"});download(blob,`volley-motion-v2-${Date.now()}.csv`)}
function exportImage(){const c=document.createElement("canvas");c.width=el.sourceVideo.videoWidth;c.height=el.sourceVideo.videoHeight;const x=c.getContext("2d");x.drawImage(el.sourceVideo,0,0);render();x.drawImage(el.overlayCanvas,0,0,c.width,c.height);c.toBlob(b=>b&&download(b,"volley-motion-frame.png"))}
function download(b,n){const u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function yt(){try{const u=new URL(el.youtubeUrl.value),p=u.hostname==="youtu.be"?u.pathname.slice(1):u.searchParams.get("v")||u.pathname.split("/").filter(Boolean).pop();if(!p)throw 0;el.youtubeFrame.src=`https://www.youtube.com/embed/${p}?playsinline=1&rel=0`;el.youtubeFrame.hidden=false;el.youtubePlaceholder.hidden=true;el.youtubeFrameWrap.classList.remove("empty")}catch{setNotice("YouTube URLを確認してください。","error")}}
function file(f){if(!f?.type.startsWith("video/")){setNotice("動画ファイルを選択してください。","error");return}if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);el.sourceVideo.src=url;el.sourceVideo.load();el.dropZone.querySelector("strong").textContent=f.name;el.dropZone.querySelector("span").textContent=`${(f.size/1048576).toFixed(1)} MB`;analysis=null;clearBall()}
function loaded(){const v=el.sourceVideo;el.clipStart.value=0;el.clipEnd.value=fmt(v.duration);el.overlayCanvas.width=v.videoWidth;el.overlayCanvas.height=v.videoHeight;[el.analyzeButton,el.playPauseButton,el.prevFrameButton,el.nextFrameButton,el.timeline,el.playbackRate].forEach(x=>x.disabled=false);el.videoStage.classList.remove("empty");el.selectBallButton.disabled=false;setNotice(`動画を読み込みました（${fmt(v.duration)}秒）。身体と手を解析してください。`,"success");if(!raf)loop()}

el.dropZone.onclick=()=>el.videoFile.click();el.videoFile.onchange=()=>file(el.videoFile.files[0]);el.dropZone.ondragover=e=>e.preventDefault();el.dropZone.ondrop=e=>{e.preventDefault();file(e.dataTransfer.files[0])};el.sourceVideo.onloadedmetadata=loaded;el.analyzeButton.onclick=analyze;el.cancelButton.onclick=()=>cancel=true;el.playPauseButton.onclick=()=>el.sourceVideo.paused?el.sourceVideo.play():el.sourceVideo.pause();el.prevFrameButton.onclick=()=>seek(el.sourceVideo.currentTime-1/60);el.nextFrameButton.onclick=()=>seek(el.sourceVideo.currentTime+1/60);el.timeline.oninput=()=>el.sourceVideo.currentTime=+el.timeline.value/1000*el.sourceVideo.duration;el.playbackRate.onchange=()=>el.sourceVideo.playbackRate=+el.playbackRate.value;el.jumpHitButton.onclick=()=>analysis?.hitIndex>=0&&seek(analysis.frames[analysis.hitIndex].time);el.setHitButton.onclick=()=>{if(!analysis)return;analysis.hitIndex=nearest(el.sourceVideo.currentTime);renderResults()};el.ballRadius.oninput=()=>el.ballRadiusLabel.textContent=`${el.ballRadius.value}px`;el.selectBallButton.onclick=selectBall;el.overlayCanvas.onclick=setBall;el.trackBallButton.onclick=trackBall;el.clearBallButton.onclick=clearBall;el.loadYoutubeButton.onclick=yt;el.exportCsvButton.onclick=exportCsv;el.exportImageButton.onclick=exportImage;[el.skeletonToggle,el.handToggle,el.ballToggle].forEach(x=>x.onchange=render);window.onbeforeunload=()=>{pose?.close();hand?.close();if(url)URL.revokeObjectURL(url)};
