'use strict';
const $=id=>document.getElementById(id);
const E={input:$('videoInput'),drop:$('dropZone'),msg:$('uploadMessage'),video:$('video'),overlay:$('overlay'),stage:$('stage'),loading:$('loadingCover'),play:$('playPause'),prev:$('prevFrame'),next:$('nextFrame'),timeline:$('timeline'),timeNow:$('timeNow'),frameNow:$('frameNow'),timeEnd:$('timeEnd'),setContact:$('setContact'),contactStatus:$('contactStatus'),markCanvas:$('markCanvas'),guideNo:$('guideNumber'),guideTitle:$('guideTitle'),guideText:$('guideText'),markProgress:$('markProgress'),undo:$('undoMark'),finish:$('finishMarks'),metrics:$('metricCards'),quality:$('qualityNotice'),contactChart:$('contactChart'),trajectoryChart:$('trajectoryChart'),insight:$('insightText'),comparison:$('comparisonSection'),comparisonBody:$('comparisonBody'),processor:$('processor')};
const FPS=30;
const state={url:null,file:null,contactTime:null,marks:[],trajectory:[],scores:[],result:null,frameImage:null,comparisons:JSON.parse(localStorage.getItem('volleyvision-comparisons')||'[]')};
const markDefs=[
 {key:'ball',title:'ボールの中心をクリック',text:'接触時のボールの中心を選びます。',color:'#ffe04b'},
 {key:'contact',title:'手が触れた位置をクリック',text:'ボール表面の接触位置を選びます。',color:'#ff4d5a'},
 {key:'wristBefore',title:'1コマ前の手首をクリック',text:'手がボールへ入ってくる方向を求めます。',color:'#62e6a7'},
 {key:'wristContact',title:'接触時の手首をクリック',text:'現在のフレームで手首の中心を選びます。',color:'#17b978'},
 {key:'palmA',title:'手のひらの左端をクリック',text:'手のひらの傾きを測る1点目です。',color:'#63a4ff'},
 {key:'palmB',title:'手のひらの右端をクリック',text:'手のひらの傾きを測る2点目です。',color:'#9d7bff'}
];
function showScreen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===`screen-${name}`));document.querySelectorAll('.step').forEach((b,i)=>{const order=['upload','review','mark','result'];b.classList.toggle('active',order[i]===name);b.classList.toggle('done',order.indexOf(name)>i)});scrollTo({top:0,behavior:'smooth'});}
function enableStep(n){document.querySelectorAll('.step').forEach((b,i)=>{if(i<=n)b.disabled=false});}
function err(t){E.msg.textContent=t;E.msg.className='message error'}
function ok(t){E.msg.textContent=t;E.msg.className='message'}
['dragenter','dragover','dragleave','drop'].forEach(type=>window.addEventListener(type,e=>{e.preventDefault();e.stopPropagation()}));
E.drop.addEventListener('dragenter',()=>E.drop.classList.add('drag'));E.drop.addEventListener('dragover',()=>E.drop.classList.add('drag'));E.drop.addEventListener('dragleave',()=>E.drop.classList.remove('drag'));E.drop.addEventListener('drop',e=>{E.drop.classList.remove('drag');const f=[...(e.dataTransfer?.files||[])].find(x=>x.type.startsWith('video/')||/\.(mp4|mov|webm|m4v)$/i.test(x.name));f?loadVideo(f):err('動画ファイルを選んでください。')});
E.input.addEventListener('change',()=>{const f=E.input.files?.[0];if(f)loadVideo(f)});
async function loadVideo(file){try{E.loading.classList.remove('hidden');state.file=file;if(state.url)URL.revokeObjectURL(state.url);state.url=URL.createObjectURL(file);E.video.pause();E.video.src=state.url;E.video.load();await waitEvent(E.video,'loadedmetadata',15000);if(!isFinite(E.video.duration)||!E.video.videoWidth)throw new Error('動画情報を取得できません');E.overlay.width=E.video.videoWidth;E.overlay.height=E.video.videoHeight;E.markCanvas.width=E.video.videoWidth;E.markCanvas.height=E.video.videoHeight;E.processor.width=Math.min(640,E.video.videoWidth);E.processor.height=Math.round(E.processor.width*E.video.videoHeight/E.video.videoWidth);E.timeline.max=Math.round(E.video.duration*1000);E.timeEnd.textContent=E.video.duration.toFixed(2)+'秒';E.video.currentTime=0;E.video.playbackRate=.25;state.contactTime=null;state.marks=[];state.trajectory=[];state.result=null;updateTime();ok(`${file.name} を読み込みました`);enableStep(1);showScreen('review')}catch(e){console.error(e);err('動画を開けませんでした。MP4（H.264）で試してください。')}finally{E.loading.classList.add('hidden')}}
function waitEvent(target,name,ms){return new Promise((res,rej)=>{if(name==='loadedmetadata'&&target.readyState>=1)return res();let t=setTimeout(()=>{clean();rej(new Error('timeout'))},ms);const yes=()=>{clean();res()},no=()=>{clean();rej(new Error('media error'))};function clean(){clearTimeout(t);target.removeEventListener(name,yes);target.removeEventListener('error',no)}target.addEventListener(name,yes,{once:true});target.addEventListener('error',no,{once:true})})}
E.play.addEventListener('click',async()=>{if(E.video.paused){await E.video.play();E.play.textContent='⏸ 一時停止'}else{E.video.pause();E.play.textContent='▶ 再生'}});E.video.addEventListener('pause',()=>E.play.textContent='▶ 再生');E.video.addEventListener('timeupdate',updateTime);E.video.addEventListener('seeked',updateTime);E.timeline.addEventListener('input',()=>E.video.currentTime=Number(E.timeline.value)/1000);E.prev.addEventListener('click',()=>step(-1));E.next.addEventListener('click',()=>step(1));function step(d){E.video.pause();E.video.currentTime=Math.max(0,Math.min(E.video.duration,E.video.currentTime+d/FPS))}function updateTime(){const t=E.video.currentTime||0;E.timeline.value=Math.round(t*1000);E.timeNow.textContent=t.toFixed(2)+'秒';E.frameNow.textContent=Math.round(t*FPS)+'コマ'}
E.setContact.addEventListener('click',async()=>{E.video.pause();state.contactTime=E.video.currentTime;E.contactStatus.textContent=`打点：${state.contactTime.toFixed(3)}秒（${Math.round(state.contactTime*FPS)}コマ）`;await captureContactFrame();state.marks=[];updateGuide();enableStep(2);showScreen('mark')});
async function captureContactFrame(){await seek(state.contactTime);const c=E.markCanvas,ctx=c.getContext('2d');ctx.drawImage(E.video,0,0,c.width,c.height);state.frameImage=ctx.getImageData(0,0,c.width,c.height);drawMarks()}
function seek(t){return new Promise(res=>{const done=()=>{E.video.removeEventListener('seeked',done);res()};if(Math.abs(E.video.currentTime-t)<.0005)return res();E.video.addEventListener('seeked',done);E.video.currentTime=Math.max(0,Math.min(E.video.duration,t))})}
E.markCanvas.addEventListener('click',async e=>{if(state.marks.length>=markDefs.length)return;const r=E.markCanvas.getBoundingClientRect(),x=(e.clientX-r.left)*E.markCanvas.width/r.width,y=(e.clientY-r.top)*E.markCanvas.height/r.height;const def=markDefs[state.marks.length];state.marks.push({key:def.key,x,y,color:def.color});drawMarks();updateGuide();if(state.marks.length===markDefs.length){E.finish.disabled=false}});
function drawMarks(){const c=E.markCanvas,ctx=c.getContext('2d');if(state.frameImage)ctx.putImageData(state.frameImage,0,0);state.marks.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,Math.max(8,c.width/110),0,Math.PI*2);ctx.fillStyle=p.color;ctx.fill();ctx.lineWidth=Math.max(2,c.width/500);ctx.strokeStyle='#fff';ctx.stroke();ctx.fillStyle='#07111e';ctx.font=`bold ${Math.max(15,c.width/55)}px sans-serif`;ctx.fillText(String(i+1),p.x+12,p.y-12)});if(state.marks.length>=4){line(ctx,state.marks[2],state.marks[3],'#50f0a6');}if(state.marks.length>=6){line(ctx,state.marks[4],state.marks[5],'#73a9ff')}}
function line(ctx,a,b,color){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.lineWidth=Math.max(4,E.markCanvas.width/220);ctx.stroke()}
function updateGuide(){const i=state.marks.length;if(i<markDefs.length){const d=markDefs[i];E.guideNo.textContent=i+1;E.guideTitle.textContent=d.title;E.guideText.textContent=d.text}else{E.guideNo.textContent='✓';E.guideTitle.textContent='準備完了';E.guideText.textContent='手とボールの点を記録しました。軌道解析へ進めます。'}E.markProgress.style.width=`${i/markDefs.length*100}%`;E.undo.disabled=i===0}
E.undo.addEventListener('click',()=>{state.marks.pop();E.finish.disabled=true;drawMarks();updateGuide()});E.finish.addEventListener('click',async()=>{E.finish.disabled=true;E.finish.textContent='解析中…';try{await trackBall();calculate();renderResult();enableStep(3);showScreen('result')}finally{E.finish.textContent='軌道を解析する';E.finish.disabled=false}});
async function trackBall(){const ball=get('ball');if(!ball)throw new Error('ball missing');const proc=E.processor,ctx=proc.getContext('2d',{willReadFrequently:true});const sx=proc.width/E.video.videoWidth,sy=proc.height/E.video.videoHeight;const start={x:ball.x*sx,y:ball.y*sy};const radius=Math.max(8,Math.round(20*sx));state.trajectory=[{x:ball.x,y:ball.y,t:state.contactTime}];state.scores=[];await seek(state.contactTime);ctx.drawImage(E.video,0,0,proc.width,proc.height);let prev=patch(ctx,start.x,start.y,radius);let pos={...start};const frames=Math.min(22,Math.max(8,Math.floor((E.video.duration-state.contactTime)*FPS)-1));for(let i=1;i<=frames;i++){await seek(state.contactTime+i/FPS);ctx.drawImage(E.video,0,0,proc.width,proc.height);let best={score:Infinity,x:pos.x,y:pos.y};const search=Math.max(18,Math.round(45*sx));for(let dy=-search;dy<=search;dy+=3){for(let dx=-search;dx<=search;dx+=3){const x=pos.x+dx,y=pos.y+dy;if(x-radius<0||y-radius<0||x+radius>=proc.width||y+radius>=proc.height)continue;const q=patch(ctx,x,y,radius);const score=diff(prev,q)+Math.hypot(dx,dy)*.12;if(score<best.score)best={score,x,y,q}}}pos={x:best.x,y:best.y};prev=best.q||prev;state.scores.push(best.score);state.trajectory.push({x:pos.x/sx,y:pos.y/sy,t:state.contactTime+i/FPS})}}
function patch(ctx,x,y,r){const d=ctx.getImageData(Math.round(x-r),Math.round(y-r),r*2,r*2).data,out=[];for(let i=0;i<d.length;i+=16)out.push((d[i]+d[i+1]+d[i+2])/3);return out}function diff(a,b){let s=0,n=Math.min(a.length,b.length);for(let i=0;i<n;i++)s+=Math.abs(a[i]-b[i]);return s/n}
function get(k){return state.marks.find(x=>x.key===k)}function angle(a,b){return Math.atan2(-(b.y-a.y),b.x-a.x)*180/Math.PI}function normAngle(a){while(a>180)a-=360;while(a<-180)a+=360;return a}function round(x,d=1){const p=10**d;return Math.round(x*p)/p}
function calculate(){const b=get('ball'),c=get('contact'),wb=get('wristBefore'),wc=get('wristContact'),pa=get('palmA'),pb=get('palmB'),tr=state.trajectory;const hand=normAngle(angle(wb,wc)),palm=normAngle(angle(pa,pb));let launch=tr.length>3?normAngle(angle(tr[0],tr[3])):NaN;const r=Math.max(1,Math.hypot(c.x-b.x,c.y-b.y));const estBallR=Math.max(12,Math.hypot(pa.x-pb.x,pa.y-pb.y)*.42);const ox=(c.x-b.x)/estBallR*100,oy=(b.y-c.y)/estBallR*100;let contactLabel=(oy>18?'上':oy<-18?'下':'中央')+(ox>18?'右':ox<-18?'左':'');if(contactLabel==='中央')contactLabel='中央';const p0=tr[0],p3=tr[Math.min(3,tr.length-1)],pn=tr[tr.length-1];const vx=p3.x-p0.x,vy=p3.y-p0.y,dt=(p3.t-p0.t)||.1;const predX=p0.x+vx*(pn.t-p0.t)/dt,predY=p0.y+vy*(pn.t-p0.t)/dt;const side=(pn.x-predX)/E.video.videoWidth*100,drop=(pn.y-predY)/E.video.videoHeight*100;const quality=state.scores.length?Math.max(0,100-Math.min(100,state.scores.reduce((a,b)=>a+b,0)/state.scores.length/1.6)):60;state.result={hand,palm,launch,ox,oy,contactLabel,side,drop,quality,file:state.file?.name||'video'}}
function renderResult(){const r=state.result;const vals=[['手の進入角',`${round(r.hand)}°`,'手首の移動方向'],['手のひら角',`${round(r.palm)}°`,'画面上の見かけ'],['接触位置',r.contactLabel,`横 ${signed(r.ox)}%／縦 ${signed(r.oy)}%`],['打ち出し角',`${round(r.launch)}°`,'接触直後'],['左右変化',`${signed(r.side)}%`,r.side>1?'右方向':r.side<-1?'左方向':'ほぼ直進'],['落下傾向',`${signed(r.drop)}%`,r.drop>1?'初期軌道より下降':'小さい'],['追跡品質',`${round(r.quality)}%`,'30fps推定']];E.metrics.innerHTML=vals.map(v=>`<div class="metric"><div class="label">${v[0]}</div><strong>${v[1]}</strong><small>${v[2]}</small></div>`).join('');E.quality.textContent=r.quality>=70?'追跡は比較的安定しています。数値をコマ送り映像と合わせて確認してください。':'追跡の信頼度は低めです。軌道図を確認し、必要なら打点と点の位置を修正してください。';E.quality.style.background=r.quality>=70?'#e8f6ed':'#fff4d8';E.quality.style.color=r.quality>=70?'#176d38':'#835d00';drawContact();drawTrajectory();E.insight.textContent=makeInsight(r);renderComparison()}
function signed(v){return `${v>=0?'+':''}${round(v)}`}
function drawContact(){const c=E.contactChart,ctx=c.getContext('2d'),r=state.result;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#f8fbff';ctx.fillRect(0,0,c.width,c.height);const x=c.width*.42,y=c.height*.5,R=115;ctx.beginPath();ctx.arc(x,y,R,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#1d5eaa';ctx.lineWidth=5;ctx.stroke();ctx.setLineDash([8,8]);ctx.strokeStyle='#b6c7da';ctx.beginPath();ctx.moveTo(x-R,y);ctx.lineTo(x+R,y);ctx.moveTo(x,y-R);ctx.lineTo(x,y+R);ctx.stroke();ctx.setLineDash([]);const px=x+r.ox/100*R,py=y-r.oy/100*R;ctx.beginPath();ctx.arc(px,py,12,0,Math.PI*2);ctx.fillStyle='#ef4444';ctx.fill();arrow(ctx,c.width*.68,c.height*.68,c.width*.68+Math.cos(-r.hand*Math.PI/180)*120,c.height*.68+Math.sin(-r.hand*Math.PI/180)*120,'#16a34a');ctx.fillStyle='#1b2d45';ctx.font='bold 24px sans-serif';ctx.fillText('接触点',px+16,py-14);ctx.fillText('手の進入方向',c.width*.58,c.height*.82)}
function drawTrajectory(){const c=E.trajectoryChart,ctx=c.getContext('2d'),tr=state.trajectory;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#f8fbff';ctx.fillRect(0,0,c.width,c.height);if(tr.length<2)return;const xs=tr.map(p=>p.x),ys=tr.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=55;const map=p=>({x:pad+(p.x-minX)/(maxX-minX||1)*(c.width-pad*2),y:pad+(p.y-minY)/(maxY-minY||1)*(c.height-pad*2)});ctx.strokeStyle='#d7e1ed';ctx.lineWidth=2;for(let i=0;i<5;i++){let yy=pad+i*(c.height-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(c.width-pad,yy);ctx.stroke()}ctx.strokeStyle='#2563eb';ctx.lineWidth=6;ctx.beginPath();tr.forEach((p,i)=>{const q=map(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke();tr.forEach((p,i)=>{const q=map(p);ctx.beginPath();ctx.arc(q.x,q.y,i===0?10:6,0,Math.PI*2);ctx.fillStyle=i===0?'#ef4444':'#59e7f2';ctx.fill();ctx.strokeStyle='#0b2140';ctx.stroke()});ctx.fillStyle='#1b2d45';ctx.font='bold 22px sans-serif';ctx.fillText('接触',pad+8,pad+28);ctx.fillText('→ 時間',c.width-130,c.height-18)}
function arrow(ctx,x1,y1,x2,y2,color){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const a=Math.atan2(y2-y1,x2-x1);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-20*Math.cos(a-.5),y2-20*Math.sin(a-.5));ctx.lineTo(x2-20*Math.cos(a+.5),y2-20*Math.sin(a+.5));ctx.closePath();ctx.fill()}
function makeInsight(r){const contact=r.contactLabel==='中央'?'ボール中心付近':`ボール中心より${r.contactLabel}`;const side=Math.abs(r.side)<1?'左右変化は小さめ':`${r.side>0?'右':'左'}方向への変化が見られます`;const drop=r.drop>1?'初期の直線軌道より下側へ外れています':'初期軌道からの落下は小さめです';return `${contact}への接触と推定されます。手の進入角は${round(r.hand)}°、打ち出し角は${round(r.launch)}°です。${side}。${drop}。30fps動画による2次元推定のため、結論は複数本の比較から判断してください。`}
$('saveComparison').addEventListener('click',()=>{state.comparisons.push({...state.result,id:Date.now()});localStorage.setItem('volleyvision-comparisons',JSON.stringify(state.comparisons));renderComparison();E.comparison.classList.remove('hidden');E.comparison.scrollIntoView({behavior:'smooth'})});function renderComparison(){if(!state.comparisons.length){E.comparison.classList.add('hidden');return}E.comparison.classList.remove('hidden');E.comparisonBody.innerHTML=state.comparisons.map((r,i)=>`<tr><td>${i+1}</td><td>${round(r.hand)}°</td><td>${round(r.palm)}°</td><td>${r.contactLabel}</td><td>${round(r.launch)}°</td><td>${signed(r.side)}%</td><td>${signed(r.drop)}%</td></tr>`).join('')}
$('clearComparison').addEventListener('click',()=>{state.comparisons=[];localStorage.removeItem('volleyvision-comparisons');renderComparison()});$('downloadCsv').addEventListener('click',()=>{const r=state.result,rows=[['file','hand_angle','palm_angle','contact','contact_x_pct','contact_y_pct','launch_angle','side_change_pct','drop_pct','quality_pct'],[r.file,r.hand,r.palm,r.contactLabel,r.ox,r.oy,r.launch,r.side,r.drop,r.quality]];const blob=new Blob(['\ufeff'+rows.map(x=>x.join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='volleyvision_result.csv';a.click();URL.revokeObjectURL(a.href)});
$('changeVideo').addEventListener('click',()=>{E.input.value='';showScreen('upload')});$('newVideo').addEventListener('click',()=>{E.input.value='';showScreen('upload')});$('backReview').addEventListener('click',()=>showScreen('review'));$('reanalyze').addEventListener('click',async()=>{state.marks=[];await captureContactFrame();updateGuide();E.finish.disabled=true;showScreen('mark')});document.querySelectorAll('.step').forEach(b=>b.addEventListener('click',()=>{if(!b.disabled)showScreen(b.dataset.go)}));renderComparison();
